### PR TITLE
Vuln db severity

### LINKED ISSUE #3589: VulnDB Vulnerabilities Always Shown as Unassigned Severity
### Current Behavior

Currently in the **latest master version**, all VulnDB vulnerabilities consistently display an “Unassigned” severity. This can be misleading for users who rely on accurate severity information. This should be addressing promptly to ensure that users receive reliable data regarding vulnerability severity. 

image

Additionally, this issue affects the new Audit Vulnerability counter integrated by PR [#736](https://github.com/DependencyTrack/frontend/pull/736). When all vulnerabilities originate from VulnDB, the severity counters will display 0 in all fields, and the green counter will also be 0.

image

### Steps to Reproduce

1. Go to the vulnerability section.
2. Examine the severity field for any VulnDB vulnerability.
3. Associate a VulnDB-related CPE with a sample component.
4. Verify the Audit Vulnerability counter after implementing the changes from PR #736.

### Expected Behavior

- The severity field should accurately reflect the severity level of each vulnerability based on available data.
- The Audit Vulnerability counter should correctly account for VulnDB vulnerabilities.

### Dependency-Track Version

4.11.0-SNAPSHOT

### Dependency-Track Distribution

Executable WAR

### Database Server

PostgreSQL

### Database Server Version

_No response_

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

### PR DESCRIPTION
**Pull request by LaVibeX**
### Description
Severity not added to VulnDB vulnerabilities. use setSeverity to fix this issue.

### Addressed Issue
Fixes #3589 

### Additional Details
Add an explicit null check and a Logger WARN message in case Vulnerability Severity is null.

### Checklist

- [X] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [X] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

File: src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java [hunk 1]
```diff
@@ -96,13 +96,16 @@ static Counters updateMetrics(final UUID uuid) throws Exception {
...
+                try {
+                    switch (vulnerability.getSeverity()) {
+                        case CRITICAL -> counters.critical++;
+                        case HIGH -> counters.high++;
+                        case MEDIUM -> counters.medium++;
+                        case LOW, INFO -> counters.low++;
+                        case UNASSIGNED -> counters.unassigned++;
+                    }
+                } catch (NullPointerException ex) {
+                    LOGGER.debug("Vulnerability severity is null for" + vulnerability.getSource() + "|" + vulnerability.getVulnId() + "->"+vulnerability.getSeverity());
```
Comment (nscuro) [inline src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java:108]: Can we make this an explicit `null` check, and log a warning instead? After the migration to v4.11, severities should no longer be `null`. If they still are, we need to know about it so we can fix it.

Comment (LaVibeX) [reply src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java:108]: Sure, let me fix it.
