### PR TITLE
download OSV mirror files to temp files to keep connection lifetime short

### LINKED ISSUE #5284: OsvDownloadTask Exception while executing Http client request: Connection reset
### Current Behavior

The following exception occurs every time the `OsvDownloadTask` is started on our DT instance: 
``` 
2025-09-03 10:33:45,119 ERROR [OsvDownloadTask] Exception while executing Http client request
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
        ...
```

This only happens for the `Ubuntu` ecosystem, which is downloaded and processed first, all other ecosystems are completed as expected: 
```
2025-09-03 10:33:45,119 INFO [OsvDownloadTask] Updating datasource with Google OSV advisories for ecosystem Debian
2025-09-03 10:39:06,685 INFO [OsvDownloadTask] Updating datasource with Google OSV advisories for ecosystem PyPI
2025-09-03 10:39:37,628 INFO [OsvDownloadTask] Updating datasource with Google OSV advisories for ecosystem Go
2025-09-03 10:39:48,623 INFO [OsvDownloadTask] Updating datasource with Google OSV advisories for ecosystem npm
2025-09-03 10:41:15,151 INFO [OsvDownloadTask] Updating datasource with Google OSV advisories for ecosystem OSS-Fuzz
2025-09-03 10:41:20,118 INFO [OsvDownloadTask] Updating datasource with Google OSV advisories for ecosystem NuGet
```

I noticed that the `all.zip` file that is downloaded for the Ubuntu ecosystem is significantly larger (~255 MB) than the files for other ecosystems, mostly because a lot of the (recent) UBUNTU advisory files are ~600 KB uncompressed.
I suspect that because these files are so large and contain a lot of information, it takes much longer to process the Ubuntu ecosystem advisory files compared to the other ecosystems. See the log snippet below (taken from the same day as above): 

```
2025-09-03 09:49:47,796 INFO [OsvDownloadTask] Updating datasource with Google OSV advisories for ecosystem Ubuntu                                                                                                                      2025-09-03 09:49:47,797 INFO [GitHubAdvisoryMirrorTask] Mirroring GHSAs that were modified since 2025-09-02T22:48:36Z
2025-09-03 09:49:47,805 INFO [LdapSyncTask] LDAP synchronization complete
2025-09-03 09:49:47,808 INFO [VulnerabilityMetricsUpdateTask] Executing metrics update on vulnerability database
2025-09-03 09:49:47,845 INFO [PortfolioMetricsUpdateTask] Executing portfolio metrics update
2025-09-03 09:49:47,847 INFO [ProjectMetricsUpdateTask] Executing metrics update for project fed1c585-fae7-4d3b-a3d9-3760c82dae63
... 
2025-09-03 09:50:41,464 INFO [EpssMirrorTask] Retrieval of epss_scores-current.csv.gz not necessary.
2025-09-03 09:50:41,464 INFO [EpssMirrorTask] EPSS mirroring complete
2025-09-03 09:50:41,464 INFO [EpssMirrorTask] Time spent (d/l):   0ms
2025-09-03 09:50:41,464 INFO [EpssMirrorTask] Time spent (parse): 0ms
2025-09-03 09:50:41,464 INFO [EpssMirrorTask] Time spent (total): 0ms
2025-09-03 10:33:45,119 ERROR [OsvDownloadTask] Exception while executing Http client request
java.net.SocketException: Connection reset
```
The exception occurs about **45 minutes after** the `OsvDownloadTask` has been started for the Ubuntu ecosystem, and it has not been completed successfully in the past weeks/months (at least as far as I can tell).
I analyzed the `inform()` method of the `OsvDownloadTask` and came to this conclusion regarding the exception: 

``` java
if (status.getStatusCode() == HttpStatus.SC_OK) {
    try (InputStream in = response.getEntity().getContent();
         ZipInputStream zipInput = new ZipInputStream(in)) {
          unzipFolder(zipInput);
    }
} 
``` 

The code above passes the `InputStream` of the requested `all.zip` file to the `unzipFolder()` method, which means that the http connection remains open for the duration of the unzipping, parsing, and processing of the advisories. As mentioned above, the Ubuntu ecosystem OSV advisories are significantly larger and I assume that this is why the processing takes so much longer for them (might also have other causes). Because the connection remains open for this long, most likely the server closes the connection at some point. 

As an ad-hoc fix I would suggest to first download the entire file (into memory or a temporary file) and then proceed with further processing.  
On my local machine I tested the suggested fix (after reproducing the exception) and the task completed after about 1.5 hours, so most likely the parsing/processing also has room for optimization. Ideally the information that is provided by the `modified_id.csv` for the specific ecosystem (see documentation here: https://google.github.io/osv.dev/data/) should be used to determine which advisories need to be (re-)acquired and processed after the initial mirror has been completed, instead of loading and processing the complete dataset each time. 

### Steps to Reproduce

1. Activate OSV mirroring
2. Wait for NIST mirroring to be completed (not sure if NVD vulnerabilities present in the db influence the processing time)
3. Add ecosystem Ubuntu and restart DT to trigger the OsvDownloadTask
4. Observe the logs

### Expected Behavior

The `OsvDownloadTask` completes successfully without exceptions being thrown

### Dependency-Track Version

4.13.4

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

17.6 alpine

### Browser

Google Chrome

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

### PR DESCRIPTION
**Pull request by stohrendorf**
### Description

Download OSV mirror files to temp files before processing them to avoid keeping connections open more than necessary.

### Addressed Issue

Fixes #5284 

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Comment by stohrendorf** [comment]
Please note that I'm happy to remove the refactoring commit since it is not directly related to the issue.

File: src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java [hunk 1]
```diff
@@ -105,32 +108,41 @@ public OsvDownloadTask() {
...
+                        out.write(in.readAllBytes());
+                    }
+                    try (final var in = new FileInputStream(tempFile); final var zipInput = new ZipInputStream(in)) {
+                        unzipFolder(zipInput);
+                    }
+                } finally {
+                    if (!tempFile.delete()) {
+                        LOGGER.warn("Failed to delete temporary file: " + tempFile.getAbsolutePath());
                     }
                 }
```
Comment (nscuro) [inline src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java]: Consider replacing this manual call to `delete` with passing [`StandardOpenOption.DELETE_ON_EXIT`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/StandardOpenOption.html#DELETE_ON_CLOSE) to [`Files.newInputStream`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/Files.html#newInputStream(java.nio.file.Path,java.nio.file.OpenOption...)).

File: src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java [hunk 2]
```diff
@@ -105,32 +108,41 @@ public OsvDownloadTask() {
...
+            try (final var ignoredMdcOsvEcosystem = MDC.putCloseable("osvEcosystem", ecosystem); final var response = HttpClientPool.getClient().execute(request)) {
+                final var status = response.getStatusLine();
+                if (status.getStatusCode() != HttpStatus.SC_OK) {
+                    LOGGER.error("Download failed : " + status.getStatusCode() + ": " + status.getReasonPhrase());
+                    continue;
+                }
+
+                final var tempFile = File.createTempFile("google-osv-download", ".zip");
+                try {
+                    try (final var out = new FileOutputStream(tempFile); final var in = response.getEntity().getContent()) {
```
Comment (nscuro) [inline src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java]: Consider using `Files.newOutputStream` here, and also wrapping the resulting stream in a [`BufferedOutputStream`](https://docs.oracle.com/javase/8/docs/api/java/io/BufferedOutputStream.html) to reduce disk I/O.

**Review by nscuro — CHANGES_REQUESTED** [review]

File: src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java [hunk 3]
```diff
@@ -105,32 +109,41 @@ public OsvDownloadTask() {
...
                 }
-            } else {
-                LOGGER.info("Google OSV mirroring is disabled. No ecosystem selected.");
+
+                final var tempFile = Files.createTempFile("google-osv-download", ".zip");
+
+                try (final var out = Files.newOutputStream(tempFile, StandardOpenOption.TRUNCATE_EXISTING);
+                     final var bufferedOut = new BufferedOutputStream(out);
+                     final var in = response.getEntity().getContent()) {
+                    bufferedOut.write(in.readAllBytes());
```
Comment (stohrendorf) [inline src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java]: I want to re-work this line so that the likelihood of an OOM error gets reduced before merge.

Comment (nscuro) [reply src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java]: [`InputStream#transferTo(OutputStream)`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/io/InputStream.html#transferTo(java.io.OutputStream)) may do the trick. This also appears to do some buffering so the `BufferedOutputStream` would be redundant then..

Otherwise, it seems [`Files#copy`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/Files.html#copy(java.io.InputStream,java.nio.file.Path,java.nio.file.CopyOption...)) achives the desired outcome in a less verbose way. It uses `InputStream#transferTo(OutputStream)` behind the scenes.
